version: '3.8'

services:
  # Redis service for caching and session storage
  redis:
    image: redis:7-alpine
    container_name: petvoa-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - petvoa-network

  # Next.js application (optional - you can run locally with npm run dev)
  # Uncomment if you want to run the app in Docker too
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: petvoa-app
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #     - REDIS_URL=redis://redis:6379
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #   networks:
  #     - petvoa-network

volumes:
  redis_data:
    driver: local

networks:
  petvoa-network:
    driver: bridge