version: '3.8'

services:
  # Redis Cache Service
  redis:
    image: redis:7-alpine
    container_name: petvoa-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - petvoa-network

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petvoa-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      # WhatsApp Config
      - NEXT_PUBLIC_WHATSAPP_NUMBER=5562983211122
      # Add your domain here
      - NEXT_PUBLIC_URL=https://petvoa.com.br
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - petvoa-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/stats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  redis_data:
    driver: local

networks:
  petvoa-network:
    driver: bridge